"""add tags emebeddings to workspace

Revision ID: 35e545cc9e3c
Revises: bffffb7b53ac
Create Date: 2026-03-18 08:35:39.858630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35e545cc9e3c'
down_revision: Union[str, Sequence[str], None] = 'bffffb7b53ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('tags_embeddings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'tags_embeddings')
    # ### end Alembic commands ###
