"""add workspace table

Revision ID: 89bd52984d8c
Revises: 69cfb99fe89b
Create Date: 2026-03-08 01:05:50.912162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bd52984d8c'
down_revision: Union[str, Sequence[str], None] = '69cfb99fe89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_organization_workspace_slug')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=False)
    op.add_column('documents', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_constraint('uq_organization_url', 'documents', type_='unique')
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_unique_constraint('uq_workspace_url', 'documents', ['workspace_id', 'url'])
    op.drop_constraint('documents_organization_id_fkey', 'documents', type_='foreignkey')
    
    op.create_foreign_key('documents_workspace_id_fkey', 'documents', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    
    op.drop_column('documents', 'organization_id')
    op.add_column('organizations', sa.Column('email', sa.String(), nullable=False))
    op.add_column('organizations', sa.Column('password_hash', sa.String(), nullable=False))
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    
    op.create_unique_constraint('organizations_email_key', 'organizations', ['email'])
    
    op.drop_column('organizations', 'slug')
    op.drop_column('organizations', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    
    op.drop_constraint('organizations_email_key', 'organizations', type_='unique')
    
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.drop_column('organizations', 'password_hash')
    op.drop_column('organizations', 'email')
    op.add_column('documents', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    
    op.drop_constraint('documents_workspace_id_fkey', 'documents', type_='foreignkey')
    
    op.create_foreign_key('documents_organization_id_fkey', 'documents', 'organizations', ['organization_id'],['id'], ondelete='CASCADE')
    op.drop_constraint('uq_workspace_url', 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.create_unique_constraint('uq_organization_url', 'documents', ['organization_id', 'url'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents',['organization_id'], unique=False)
    op.drop_column('documents', 'workspace_id')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###