"""add is_approved to document

Revision ID: b989bcccd440
Revises: b79bc0f71a3c
Create Date: 2026-03-12 20:18:33.036054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b989bcccd440'
down_revision: Union[str, Sequence[str], None] = 'b79bc0f71a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_approved', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_documents_is_approved'), 'documents', ['is_approved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_is_approved'), table_name='documents')
    op.drop_column('documents', 'is_approved')
    # ### end Alembic commands ###
